// ── Shared TypeScript types for TaskFlow ────────────────────────────────────
// These mirror the Supabase `tasks` table schema exactly.
// Used by lib/supabase.ts, all Server Components, and all Client Components.

/** The two strict task categories defined in the PRD. */
export type Category = 'Academic' | 'Skill Acquisition';

/** Matches the `tasks` table row structure returned by Supabase. */
export interface Task {
  id: string;            // UUID, auto-generated by Supabase
  title: string;         // Short name of the task
  description: string | null; // Optional detailed notes or links
  category: Category;    // 'Academic' | 'Skill Acquisition'
  due_date: string;      // ISO 8601 timestamp string (from Supabase TIMESTAMPTZ)
  is_completed: boolean; // Default false
  created_at: string;    // ISO 8601 timestamp, auto-generated
}

/** Used for INSERT operations — id and created_at are auto-generated by the DB. */
export type NewTask = Omit<Task, 'id' | 'created_at'>;

/** Used for UPDATE operations — all fields optional except id. */
export type TaskUpdate = Partial<Omit<Task, 'id' | 'created_at'>> & { id: string };
